# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: 小火
title: 软件工程师
email: xiaohuo200@gmail.com
website: https://renlulu.github.io/

# Social links
twitter_username: xiaohuo200
github_username:  renlulu
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
#linkedin_username: jameswgrant
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: 关于我
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  你好，我叫小火。我是一名软件工程师，目前在上海一家初创区块链公司任研发总监，主要负责区块链相关的产品研发和管理工作。同时我也是区块链技术社区 FireStack
  的联合创始人。我在 2016年开始接触区块链技术，并为联盟链项目 R3 Corda 贡献代码和社区项目，成为其 contributor。此后主要精力投向公链技术，在公链项目 Zilliqa
  的 grant 资助下，已完成并交付 Zilliqa go sdk 和 java sdk；并参与对接 Binance，OKEx，KuCoin 等多家交易所和钱包。同时，我也是《精通以太坊》
  （机械工业出版社 ISBN：9787111624929）的联合译者。个人公众号：Monad实验室。

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience


# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
